---
- hosts: all
  become: true
  tasks:
    - name: install packages
      package:
        name:
          - ubuntu-desktop
          - tigervnc-standalone-server
          - gnome-panel
          - gnome-settings-daemon
          - metacity
          - nautilus
          - gnome-terminal
          - gnome-tweaks
          - gnome-shell
          - gnome-shell-extensions
          - gnome-tweak-tool
        state: latest
    - name: update settings
      shell: |
        gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com
        gnome-extensions enable ubuntu-dock@ubuntu.com
        gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
        gsettings set org.gnome.desktop.wm.preferences theme "Yaru"
        gsettings set org.gnome.shell.extensions.user-theme name "Yaru-dark"
        gsettings set org.gnome.desktop.interface gtk-theme "Yaru"
        gsettings set org.gnome.desktop.interface icon-theme "Yaru"
