---
host: default
become: true
  tasks:
    - name: install packages
      package:
        name:
          - ubuntu-desktop
          - tigervnc-standalone-server
          - gnome-panel
          - gnome-settings-daemon
          - metacity
          - nautilus
          - gnome-terminal
          - gnome-tweaks
          - gnome-shell
    - name: update settings
      shell: |
        gnome-extensions enable user-theme
        gnome-extensions enable ubuntu-dock@ubuntu.com
        gnome-extensions enable dash-to-dock@micxgx.gmail.com
        gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
        gsettings set org.gnome.desktop.wm.preferences theme "Yaru"
        gsettings set org.gnome.shell.extensions.user-theme name "Yaru"
        gsettings set org.gnome.desktop.interface gtk-theme "Yaru"
